#!/bin/bash

# change to the test output directory
cd $1

key_test() {
    cat "$1" | grep -i -q "$2"
}

warning=false
failure=$(cat failure-step)

if key_test passed true; then
    if key_test has-warning true; then
        warning=true
    else
        echo "Test passed, do nothing"
        exit 0
    fi
fi

if [[ "$failure" = "apply" ]]; then
    # Don't complain about apply failure for now
    echo "Ignoring apply failure"
    exit 0
fi

cat >mail <<EOF
Subject: Re: $(cat subject | tr -d '\n')
From: Patchew Tool <patchew.tool@gmail.com>
To: qemu-devel@nongnu.org
In-Reply-To: $(cat message-id | tr -d '\n')

EOF

showlink()
{
    python -c 'import urllib, sys; print urllib.quote_plus(sys.argv[1])' \
        "http://qemu.patchew.org/testing/log/$(cat message-id)"
}

if $warning; then

    cat <<EOF

This series passed Patchew automatic testing, but there are some warnings.

Find the log fragments below, or open the following URL to see the full log:

$(showlink)

----------8<---------

$(cat log | grep -C 10 '<<< WARNING >>>' | sed -e 's/<<< WARNING >>>//g')

EOF

else

    cat <<EOF

This series failed Patchew automatic testing.

Find the log fragments below (grepped lines around keywords "error" and
"warning"), or open the following URL to see the full log:

$(showlink)

----------8<---------

$(cat log | grep -w -i -C 20 -e warning -e error | sed -e 's/<<< WARNING >>>//g')

EOF

fi >> mail

# Assume that msmtp is properly configured
msmtp -t < mail
