#!/bin/bash

# change to the test output directory
cd $1

key_test() {
    cat "$1" | grep -i -q "$2"
}

warning=false
failure=$(cat failure-step)

if key_test passed true; then
    if key_test has-warning true; then
        warning=true
    else
        echo "Test passed, do nothing"
        exit 0
    fi
fi

if [[ "$failure" = "apply" ]]; then
    # Don't complain about apply failure for now
    echo "Ignoring apply failure"
    exit 0
fi

cat >mail <<EOF
Subject: Re: $(cat subject | tr -d '\n')
From: Patchew Tool <patchew.tool@gmail.com>
To: famz@redhat.com
Cc: fam@euphon.net
In-Reply-To: $(cat message-id | tr -d '\n')

EOF

if $warning; then

    cat <<EOF

This series passed Patchew automatic testing, but there are some warnings:

...
$(cat log | grep -C 10 '<<< WARNING >>>' | sed -e 's/<<< WARNING >>>//g')
...

EOF

else

    cat <<EOF

This series failed $failure in Patchew automatic testing, see log
below:

----------8<----------

$(cat log)

EOF

fi >> mail

# Assume that msmtp is properly configured
msmtp -t < mail
