#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

LOG=$OPENSHIFT_TMP_DIR/patchew-deploy.$$.log
do_work()
{
    if ! $@ > $LOG; then
        cat $LOG
        return 1
    fi
}

echo "Migrating database..."
do_work python "$OPENSHIFT_REPO_DIR"/manage.py migrate --noinput &>$LOG
echo "Collecting static files..."
do_work python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput

echo "Initializing media directory..."
mkdir -p $OPENSHIFT_DATA_DIR/media
if ! test -h $OPENSHIFT_REPO_DIR/wsgi/static/media; then
    ln -s $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media
fi

rm -f $LOG
