#!/usr/bin/env python3
#
# Copyright 2016 Red Hat, Inc.
#
# Authors:
#     Fam Zheng <famz@redhat.com>
#
# This work is licensed under the MIT License.  Please see the LICENSE file or
# http://opensource.org/licenses/MIT.

import sys
import os
from patchewtest import PatchewTestCase, main
import json

class ImportTest(PatchewTestCase):

    def setUp(self):
        self.start_server()
        self.login()
        self.check_cli_command("project", "add", "QEMU",
                               "--mailing-list", "qemu-devel@nongnu.org")

    def tearDown(self):
        self.stop_server()

    def test_import_one(self):
        self.check_cli_command("import", self.get_data_path("0001-simple-patch.mbox.gz"))
        a, b = self.check_cli_command("search")
        self.assertIn('[Qemu-devel] [PATCH] quorum: Only compile when supported',
                      a.splitlines())

    def test_import_belong_to_multiple_projects(self):
        self.login()
        self.check_cli_command("project", "add", "QEMU2",
                               "--mailing-list", "qemu-devel@nongnu.org")
        self.check_cli_command("import", self.get_data_path("0001-simple-patch.mbox.gz"))
        a, b = self.check_cli_command("search")
        self.assertEqual(2,
            a.splitlines().count('[Qemu-devel] [PATCH] quorum: Only compile when supported'))

    def test_case_insensitive(self):
        self.check_cli_command("import",
                               self.get_data_path("0002-unusual-cased-tags.mbox.gz"))
        a, b = self.check_cli_command("search", "-r")
        ao = json.loads(a)[0]
        self.assertEqual(["Fam Zheng", "famz@redhat.com"],
                         ao["properties"]["reviewers"][0])
        self.assertIn('Reviewed-By: Fam Zheng <famz@redhat.com>',
                      ao["properties"]["tags"])
        self.assertIn('tESTed-bY: Fam Zheng <famz@redhat.com>',
                      ao["properties"]["tags"])

class UnprivilegedImportTest(ImportTest):
    def setUp(self):
        self.start_server()
        self.create_user("importer", "importerpass", False, ["importers"])
        self.login()
        self.check_cli_command("project", "add", "QEMU",
                               "--mailing-list", "qemu-devel@nongnu.org")
        self.logout()
        self.login("importer", "importerpass")

    test_import_belong_to_multiple_projects = None

    def check_import_should_fail(self):
        r, a, b = self.cli_command("import",
                                   self.get_data_path("0001-simple-patch.mbox.gz"))
        self.assertNotEqual(r, 0)
        a, b = self.check_cli_command("search")
        self.assertNotIn('[Qemu-devel] [PATCH] quorum: Only compile when supported',
                         a.splitlines())

    def test_anonymous_import(self):
        self.logout()
        self.check_import_should_fail()

    def test_normal_user_import(self):
        self.logout()
        self.create_user("someuser", "somepass", False)
        self.login("someuser", "somepass")
        self.check_import_should_fail()

if __name__ == '__main__':
    main()
