#!/usr/bin/env python
import sys
import os
from patchewtest import PatchewTestCase, main

class StartStopTest(PatchewTestCase):
    def test_start_stop(self):
        self.start_server()
        self.stop_server()

if __name__ == '__main__':
    main()

