#!/usr/bin/env python
import sys
import os
from patchewtest import PatchewTestCase, main

class ImportTest(PatchewTestCase):

    def setUp(self):
        self.start_server()
        self.login()

    def tearDown(self):
        self.stop_server()

    def test_import_one(self):
        self.check_cli_command("project", "add", "QEMU",
                               "--mailing-list", "qemu-devel@nongnu.org")
        self.check_cli_command("import", self.get_data_path("0001-simple-patch.mbox.gz"))
        a, b = self.check_cli_command("search")
        self.assertIn('[Qemu-devel] [PATCH] quorum: Only compile when supported',
                      a.splitlines())

if __name__ == '__main__':
    main()

