#!/usr/bin/env python3
#
# Copyright 2016 Red Hat, Inc.
#
# Authors:
#     Fam Zheng <famz@redhat.com>
#
# This work is licensed under the MIT License.  Please see the LICENSE file or
# http://opensource.org/licenses/MIT.

import sys
import os
from patchewtest import PatchewTestCase, main

class StartStopTest(PatchewTestCase):
    def test_start_stop(self):
        self.start_server()
        self.stop_server()

if __name__ == '__main__':
    main()

