#!/usr/bin/env python
import sys
import os
from patchewtest import PatchewTestCase, main

class ProjectTest(PatchewTestCase):

    def setUp(self):
        self.start_server()
        self.login()

    def tearDown(self):
        self.stop_server()

    def test_empty(self):
        a, b = self.check_cli_command("project")
        self.assertFalse(a)
        self.assertFalse(b)

    def add_one_project(self, name):
        self.check_cli_command("project", "add", name)
        a, b = self.check_cli_command("project")
        self.assertIn(name, a.splitlines())
        self.assertEqual(b, "")

    def test_add_one(self):
        self.add_one_project("TestProject")

    def test_add_multiple(self):
        projects = ["TestProject-%d" % x for x in range(5)]
        for p in projects:
            self.add_one_project(p)
        a, b = self.check_cli_command("project")
        for p in projects:
            self.assertIn(p, a.splitlines())

    def test_duplicated(self):
        self.add_one_project("TestProject")
        r, a, b = self.cli_command("project", "add", "TestProject")
        self.assertNotEqual(r, 0)
        self.assertNotEqual(b, "")

if __name__ == '__main__':
    main()

