# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('text', models.TextField(blank=True)),
                ('module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Module')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moduleasset',
            unique_together=set([('module', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='moduledata',
            unique_together=set([('module', 'name')]),
        ),
    ]
