# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160630_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_reply_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
