# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_last_reply_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduleasset',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduleasset',
            name='module',
        ),
        migrations.AlterUniqueTogether(
            name='moduledata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduledata',
            name='module',
        ),
        migrations.DeleteModel(
            name='ModuleAsset',
        ),
        migrations.DeleteModel(
            name='ModuleData',
        ),
    ]
