# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160707_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproperty',
            name='name',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
