# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160725_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
