# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
    ]
