# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170627_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='num_patches',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
