# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message_num_patches'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproperty',
            name='blob',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectproperty',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
