# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170706_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageproperty',
            name='blob',
            field=models.BooleanField(default=False),
        ),
    ]
