# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_messageproperty_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageproperty',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
