# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170706_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
    ]
