# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message_is_merged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prefix_tags',
            field=models.CharField(blank=True, help_text='Whitespace separated tags that\n                                   are required to be present messages\' prefix.\n                                   Tags led by \'/\' are treated with python regex match.\n                                   Tags led by "!" mean these mustn\'t exist.\n                                   ', max_length=1024),
        ),
    ]
