# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message_is_merged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('maintainers', models.TextField()),
                ('patches', models.TextField(blank=True, default='[]')),
                ('auto_props', models.TextField(blank=True, default='[]')),
                ('auto_branch', models.BooleanField(default=True)),
                ('need_rebase', models.BooleanField(default=False)),
                ('repo', models.CharField(blank=True, help_text='The git repo of the queue', max_length=4096)),
                ('branch', models.CharField(blank=True, help_text="The name of the queue's branch", max_length=4096)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='prefix_tags',
            field=models.CharField(blank=True, help_text='Whitespace separated tags that\n                                   are required to be present messages\' prefix.\n                                   Tags led by \'/\' are treated with python regex match.\n                                   Tags led by "!" mean these mustn\'t exist.\n                                   ', max_length=1024),
        ),
        migrations.AddField(
            model_name='queue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set([('project', 'name')]),
        ),
    ]
