# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171203_0635'),
        ('api', '0016_auto_20171104_1411'),
    ]

    operations = [
    ]
