# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171203_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectproperty',
            options={'verbose_name_plural': 'Project Properties'},
        ),
    ]
