# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171203_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_comment_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
