# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fix_recipients_utf8'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='Parent project which this\n                                       project belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
