# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_project_parent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='Parent project which this\n                                       project belongs to. The parent must be a\n                                       top project which has\n                                       parent_project=NULL', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
