# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 16:54
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_deblob_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageproperty',
            name='blob',
        ),
        migrations.RemoveField(
            model_name='projectproperty',
            name='blob',
        ),
        migrations.AlterField(
            model_name='messageproperty',
            name='value',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='projectproperty',
            name='value',
            field=jsonfield.fields.JSONField(),
        ),
    ]
