# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_fix_project_attr_help_texts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='enabled',
        ),
    ]
