# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0041_postgres_fts'),
    ]

    operations = [
        migrations.RenameModel('Review', 'QueuedSeries'),
    ]
