# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0043_auto_20181120_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Watched query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
