# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 12:56
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_message_maintainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=jsonfield.fields.JSONField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
    ]
