# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_populate_project_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
    ]
