# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_populate_property_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messageproperty',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='messageproperty',
            name='message',
        ),
        migrations.AlterUniqueTogether(
            name='projectproperty',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectproperty',
            name='project',
        ),
        migrations.DeleteModel(
            name='MessageProperty',
        ),
        migrations.DeleteModel(
            name='ProjectProperty',
        ),
    ]
