# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_populate_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_series_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together=set([('topic', 'date'), ('topic', 'project', 'last_reply_date'), ('topic', 'project', 'date'), ('topic', 'last_reply_date')]),
        ),
    ]
