# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-16 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_repopulate_series_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_series_head',
        ),
    ]
