# Generated by Django 3.1.14 on 2022-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_broken_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mbox_bytes',
            field=models.BinaryField(),
        ),
    ]
