# Generated by Django 3.1.14 on 2022-04-11 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0064_auto_20220407_0742'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queuedseries',
            unique_together={('user', 'name', 'message')},
        ),
    ]
