# Generated by Django 3.1.14 on 2022-09-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20220919_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectresult',
            name='project',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='project_denorm',
            new_name='project',
        ),
    ]
