# Generated by Django 3.1.14 on 2022-09-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20220919_1008'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='result',
            index_together={('status', 'name', 'project')},
        ),
    ]
