# Generated by Django 3.1.14 on 2022-09-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20220919_1016'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='message',
            index_together={('topic', 'last_reply_date'), ('project', 'topic', 'date'), ('project', 'topic', 'last_reply_date'), ('topic', 'date')},
        ),
    ]
