#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# Authors:
#     Fam Zheng <famz@redhat.com>
#
# This work is licensed under the MIT License.  Please see the LICENSE file or
# http://opensource.org/licenses/MIT.

set -e
if [ $# -lt 1 ]; then
    echo "usage: $0 <remote>"
    exit 1
fi

remote="root@$1"

if ! test -f README.md; then
    echo "Must run from project root"
    exit 1
fi

tester_setup()
{
    local conf="$HOME/.patchew-tester/config"
    if ! test -f "$conf"; then
        # Generate default config
        mkdir -p $(dirname "$conf")
        cat >$conf <<EOF
# Patchew tester deploy config:
PATCHEW_SERVER=http://localhost:8000
PATCHEW_UESR=somebody
PATCHEW_PASS=password001
PATCHEW_TESTER_PROJECT=myproject

EOF
    fi
    cp $conf $conf.new
    $EDITOR $conf.new
    if test -z "$(cat $conf.new)"; then
        echo "empty config, quit"
        rm $conf.new
    fi
    mv $conf.new $conf
    ssh $remote mkdir -p /etc/patchew
    scp $conf $remote:/etc/patchew/tester.conf
}

tester_setup

echo "Copy patchew-tester"
scp scripts/patchew-tester $remote:/usr/bin/patchew-tester
echo "Copy patchew-cli"
scp patchew-cli $remote:/usr/bin/patchew
echo "Copy patchew-tester.service"
scp patchew-tester.service $remote:/usr/lib/systemd/system/
echo "Create user 'patchew'"
ssh $remote useradd -m -s /bin/bash patchew || true
echo "Enable patchew-tester systemd service"
ssh $remote systemctl stop patchew-tester &>/dev/null || true
ssh $remote systemctl enable patchew-tester
echo "Start patchew-tester systemd service"
ssh $remote systemctl start patchew-tester
