#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# Authors:
#     Fam Zheng <famz@redhat.com>
#
# This work is licensed under the MIT License.  Please see the LICENSE file or
# http://opensource.org/licenses/MIT.

set -e
if [ $# -lt 1 ]; then
    echo "usage: $0 <remote>"
    exit 1
fi

remote="$1"

DOCKER=${DOCKER:-"sudo docker"}

if ! test -f README.md; then
    echo "Must run from project root"
    exit 1
fi

REMOTE_COPY=/tmp/patchew-deploy
rsync --exclude=.git --delete -azrC . $remote:$REMOTE_COPY

importer_setup()
{
    local conf="$HOME/.patchew-importer/config"
    if ! test -f "$conf"; then
        # Generate default config
        mkdir -p $(dirname "$conf")
        cat >$conf <<EOF
# Patchew importer deploy config:
PATCHEW_SERVER=http://localhost:8000
PATCHEW_UESR=somebody
PATCHEW_PASS=password001
# Methods: offlineimap, archive
PATCHEW_IMPORT_METHOD=offlineimap

# Imap setting to fetch email
IMAP_SERVER=imap.gmail.com
IMAP_USER=myusername
IMAP_PASS=mypassword
IMAP_SSL=yes
# SHA1 fingerprint of the imap server certificate
IMAP_CERT_FINGERPRINT=
IMAP_FOLDERS=qemu-devel

IMAP_DELETE_AFTER_IMPORT=

ARCHIVE_URL=

EOF
    fi
    cp $conf $conf.new
    ${EDITOR:-vi} $conf.new
    if test -z "$(cat $conf.new)"; then
        echo "empty config, quit"
        rm $conf.new
    fi
    mv $conf.new $conf
    scp $conf $remote:$REMOTE_COPY/patchew-importer.config
}

importer_setup

ssh -t $remote "\
    $DOCKER stop patchew-importer 2>/dev/null; \
    $DOCKER rm -f patchew-importer 2>/dev/null; \
    $DOCKER tag patchew:importer patchew:importer-prev 2>/dev/null; \
    cd $REMOTE_COPY; \
    $DOCKER build -t patchew:importer -f importer.docker .; \
    $DOCKER run --name patchew-importer \
        -d $extra_opts \
        -v /data:/data \
        patchew:importer; \
    $DOCKER rmi patchew:importer-prev 2>/dev/null;
    cd /;
    rm $REMOTE_COPY -rf"
