#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# Authors:
#     Fam Zheng <famz@redhat.com>
#
# This work is licensed under the MIT License.  Please see the LICENSE file or
# http://opensource.org/licenses/MIT.

set -e
if [ $# -lt 1 ]; then
    echo "usage: $0 <remote>"
    exit 1
fi

remote="$1"

DOCKER=${DOCKER:-"sudo docker"}

if ! test -f README.md; then
    echo "Must run from project root"
    exit 1
fi

REMOTE_COPY=/tmp/patchew-deploy
rsync --exclude=.git --delete -azrC . $remote:$REMOTE_COPY

ssh -t $remote "\
    $DOCKER stop patchew-server 2>/dev/null;
    $DOCKER rm -f patchew-server 2>/dev/null;
    $DOCKER tag patchew:server patchew:server-prev 2>/dev/null;
    cd $REMOTE_COPY;
    $DOCKER build -t patchew:server -f server.docker .;
    $DOCKER rmi patchew:server-prev 2>/dev/null;
    sudo cp patchew-server.service /etc/systemd/system;
    sudo systemctl restart patchew-server;
    cd /; rm $REMOTE_COPY -rf;
"
