#! /bin/sh

verbose=false
case "$1" in
  --verbose|-v) verbose=: ;;
esac

run() {
  echo Running "$*"
  ($verbose || exec >/dev/null
   "$@")
}

if ! test -f patchew-db-small.tar.xz; then
  echo Downloading sample database...
  wget http://people.redhat.com/pbonzini/patchew-db-small.tar.xz
fi

if test -d venv; then
  echo Virtual environment already present in $PWD/venv
  echo To start from scratch, rerun scripts/developer-setup after typing
  echo
  echo "    git clean -Xdf"
else
  run python3 -m venv ./venv
  . venv/bin/activate
  export PYTHONPATH=.
  run tar xf patchew-db-small.tar.xz
  run pip install -r requirements.txt
  run easy_install gunicorn
  run ./manage.py migrate --noinput
  run ./manage.py collectstatic --noinput
  echo
  echo Virtual environment created in $PWD/venv
fi
echo
echo To activate the virtual environment, try
echo
echo "    . venv/bin/activate"
echo "    export PYTHONPATH=."
echo
echo To run tests, try
echo
echo "    ./manage.py test tests"
echo
echo To start a web server on http://127.0.0.1:8000, try
echo
echo "    ./manage.py runserver"
echo
