#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# Authors:
#     Fam Zheng <famz@redhat.com>
#
# This work is licensed under the MIT License.  Please see the LICENSE file or
# http://opensource.org/licenses/MIT.

set -e

CONFIG="/etc/patchew/tester.conf"

while getopts "c:" FLAG; do
    case $FLAG in
        c)  #set option "c"
            echo $OPTARG
            CONFIG=$OPTARG
            ;;
    esac
done

. $CONFIG


patchew --nodebug -s "$PATCHEW_SERVER" login "$PATCHEW_UESR" "$PATCHEW_PASS"
patchew --nodebug -s "$PATCHEW_SERVER" tester -p "$PATCHEW_TESTER_PROJECT"
